# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-is-friendly}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["RipTheJacker"]
  s.date = %q{2011-04-08}
  s.email = %q{kabari@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/dm-is-friendly.rb",
    "lib/dm-is-friendly/is/friendly.rb",
    "spec/dm-is-friendly_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/RipTheJacker/dm-is-friendly}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{DataMapper plugin that adds self-referential friendship functionality to your models.}
  s.test_files = [
    "spec/dm-is-friendly_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.1.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_development_dependency(%q<dm-aggregates>, ["~> 1.1.0"])
      s.add_development_dependency(%q<dm-types>, ["~> 1.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.0.2"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.1.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_dependency(%q<dm-aggregates>, ["~> 1.1.0"])
      s.add_dependency(%q<dm-types>, ["~> 1.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<dm-core>, ["~> 1.0.2"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.1.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.4"])
    s.add_dependency(%q<dm-aggregates>, ["~> 1.1.0"])
    s.add_dependency(%q<dm-types>, ["~> 1.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<dm-core>, ["~> 1.0.2"])
  end
end

